
all:	result.vcd
result.vcd:	counter.vhdl	counterTest.vhdl
	ghdl	-a	-fsynopsys	counter.vhdl
	ghdl	-a	counter.vhdl
	ghdl	-e	-fsynopsys tb_counter
	ghdl	-r	-fsynopsys tb_counter	--vcd=result.vcd	--stop-time=20us
clean:
	rm	-rf	result.vcd
